version: '3'
services: 
  xrayr: 
    container_name: xrayr
    image: crackair/xrayr:latest
    volumes:
      - ./config:/etc/XrayR/ # 映射配置文件夹
      - /etc/nginx/ssl:/ec/XrayR/ssl
    restart: always
    network_mode: host
